name: Build and test
on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'neural-strata/remote-build-android-source'
          ref: 'main'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - uses: actions/cache@v2
        with:
          path: |
            ./build
            ./app/build/
          key: shared-build-cache-${{ hashFiles('**/*.gradle*') }}

      - name: Build project
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: ./app/build/outputs/

  test:
    needs: build
    timeout-minutes: 30
    runs-on: macos-latest # macos enables hardware acceleration in the virtual machine
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
    strategy:
      matrix:
        api-level: [ 26 ]
        target: [ google_apis ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'neural-strata/remote-build-android-source'
          ref: 'main'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: darwin-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - uses: actions/cache@v2
        with:
          path: |
            /usr/local/lib/android/sdk/build-tools/30.0.3
            /usr/local/lib/android/sdk/platform-tools
            /usr/local/lib/android/sdk/emulator
            /usr/local/lib/android/sdk/tools
            /usr/local/lib/android/sdk/platforms
            /Users/runner/Library/Android/sdk/platforms
            /Users/runner/Library/Android/sdk/build-tools/30.0.3
            /Users/runner/Library/Android/sdk/platform-tools
            /Users/runner/Library/Android/sdk/emulator
            /Users/runner/Library/Android/sdk/tools
          key: darwin-build-tools-android-sdk-${{ matrix.api-level }}-${{ hashFiles('**/.github/workflows/*android.*.yml') }}

      - uses: actions/cache@v2
        with:
          path: |
            /usr/local/lib/android/sdk/system-images
            /Users/runner/Library/Android/sdk/system-images
          key: darwin-system-images-android-sdk-${{ matrix.api-level }}

      - uses: actions/cache@v2
        with:
          path: |
            ./build
            ./app/build/
          key: darwin-shared-build-cache-${{ hashFiles('**/*.gradle*') }}

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86
          disable-animations: true
          script: |
            adb devices
            ./gradlew connectedCheck --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: app/build/reports
